name: agrobid
description: Agrobid is an online platform to bid farming products.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  bottom_navy_bar: ^5.6.0
  cloud_firestore: ^1.0.2
  cupertino_icons: ^1.0.1
  customize: ^0.0.5
  firebase_auth: ^1.0.1
  firebase_core: ^1.0.2
  firebase_storage: ^8.0.2
  flutter_svg: ^0.19.3
  font_awesome: ^5.10.1
  form_field_validator: ^1.1.0
  get: ^3.25.6
  http: ^0.13.1
  image_picker: ^0.7.2+1
  intl: ^0.17.0
  url_launcher: ^6.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
